"""
TAS-grounded agent: BasicAgent subclass that injects Steel Axe% TAS demonstrations
into the system prompt before each run.

The TAS trajectory is loaded from research/data/tas_trajectory.json (generated by
research/scripts/parse_tas.py). A configurable number of steps are prepended as a
few-shot example block.
"""

import json
import re
from pathlib import Path
from typing import Optional

from fle.agents.basic_agent import BasicAgent


# ---- Coordinate abstraction -----------------------------------------------
# TAS coordinates are map-specific (steelaxe% fixed seed).
# We abstract positional steps to patterns so the LLM learns sequencing,
# not specific coordinates that won't transfer to FLE's lab scenarios.

def abstract_position(fle_call: str) -> str:
    """Replace hardcoded coordinates with generic valid-Python equivalents."""
    # move_to((x, y)) -> move_to(nearest_position)
    if fle_call.startswith("move_to"):
        return re.sub(r"move_to\([^)]+\)", "move_to(nearest_resource_position)", fle_call)
    # harvest_resource(nearest('resource', (x, y))) -> harvest_resource(nearest('resource'))
    if "harvest_resource" in fle_call:
        return re.sub(r"nearest\('resource',\s*\([^)]+\)\)", "nearest('resource')", fle_call)
    # place_entity: strip position kwarg entirely - direction + entity name is the useful signal
    if "place_entity" in fle_call:
        return re.sub(r",\s*position=\([^)]+\)", "", fle_call)
    # extract_item / insert_item: strip position from nested get_entity call
    if "get_entity" in fle_call:
        return re.sub(r"get_entity\(position=\([^)]+\)\)", "get_entity(position=nearest_entity_position)", fle_call)
    return fle_call


def build_few_shot_prompt(trajectory: list, n: int, abstract: bool = True) -> str:
    lines = [
        "## Expert Demonstration: Steel Axe% Speedrun (7:35 optimal)",
        "",
        "The sequence below is the first phase of an optimal early-game run.",
        "Use it as a reference for **ordering**: when to research, when to build,",
        "when to craft vs mine. Do not copy coordinates literally - adapt to your map.",
        "",
        "```python",
    ]

    for entry in trajectory[:n]:
        call = abstract_position(entry["fle"]) if abstract else entry["fle"]
        lines.append(f"# step {entry['step']} ({entry['action']})")
        lines.append(call)

    lines += [
        "```",
        "",
        "**Key patterns from this demonstration:**",
        "- Place burner-mining-drill + stone-furnace as the very first action",
        "- Fuel both with wood immediately",
        "- Queue research (automation -> steel-processing -> steel-axe) early,",
        "  *before* smelting is complete - do not wait",
        "- Craft iron-gear-wheels in batches to minimize trips",
        "- mine() and craft_item() can overlap with walking - chain them",
        "",
    ]

    return "\n".join(lines)


# ---- Agent ----------------------------------------------------------------

class TASGroundedAgent(BasicAgent):
    """
    BasicAgent with TAS few-shot demonstrations injected into the system prompt.

    Args:
        model: Ollama model string, e.g. "ollama-qwen2.5-coder:14b"
        task: FLE task object
        tas_steps: Number of TAS steps to inject (default 40)
        abstract_coords: Replace map-specific coordinates with descriptions (default True)
        trajectory_path: Path to tas_trajectory.json
    """

    def __init__(
        self,
        model: str,
        task,
        tas_steps: int = 40,
        abstract_coords: bool = True,
        trajectory_path: Optional[Path] = None,
        **kwargs,
    ):
        trajectory_path = trajectory_path or Path("research/data/tas_trajectory.json")

        if not trajectory_path.exists():
            raise FileNotFoundError(
                f"TAS trajectory not found at {trajectory_path}. "
                "Run: python research/scripts/parse_tas.py"
            )

        with open(trajectory_path) as f:
            trajectory = json.load(f)

        tas_prompt = build_few_shot_prompt(trajectory, n=tas_steps, abstract=abstract_coords)
        self.tas_steps_injected = tas_steps

        super().__init__(model=model, system_prompt=tas_prompt, task=task, **kwargs)
